### ISSUE TITLE
Virtualbox builder has wrong "guest_os_type"

### ISSUE THREAD

**Issue by rquarry** [eaksel/packer-Win10#1]
Really enjoyed using this code to build windows 10 VM's, thank you! I noticed the builder has the OS as:
```json
{
  "type": "virtualbox-iso",
            "guest_os_type": "Windows2016_64",
}
```
Since the repo builds windows 10 it could/should be:
```json
{
  "type": "virtualbox-iso",
            "guest_os_type": "Windows10_64",
}
```
Are you interested on pull requests for things like this?

**Comment by eaksel** [comment]
Hi @rquarry ,

I'm happy to hear that you're enjoying it :)

Thanks for noticing it, feel free to create a PR and I'll gladly merge it.
